version: '3.9'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opt:
      type: none
      o: bind
      device: /home/adam/Desktop/Inception/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opt:
      type: none
      o: bind
      device: /home/adam/Desktop/Inception/wordpress

networks:
  inception:
    driver: bridge